-- Generic email-waterfall client provisioning.
-- New clients get public.{tag}_wf_companies / {tag}_wf_contacts.

CREATE TABLE IF NOT EXISTS public.ew_clients (
  client_tag text PRIMARY KEY,
  display_name text,
  companies_table text NOT NULL,
  contacts_table text NOT NULL,
  profile text NOT NULL DEFAULT 'owner',
  titles jsonb NOT NULL DEFAULT '[]'::jsonb,
  icp text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ew_clients TO service_role;

CREATE OR REPLACE FUNCTION public.ew_ensure_client(
  p_client_tag text,
  p_display_name text DEFAULT NULL,
  p_profile text DEFAULT 'owner',
  p_icp text DEFAULT NULL,
  p_titles jsonb DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  safe text;
  companies text;
  contacts text;
  profile text;
  titles jsonb;
  created_companies boolean := false;
  created_contacts boolean := false;
BEGIN
  safe := lower(regexp_replace(coalesce(p_client_tag, ''), '[^a-z0-9_]', '', 'g'));
  IF safe IS NULL OR safe = '' OR safe !~ '^[a-z][a-z0-9_]{0,46}$' THEN
    RAISE EXCEPTION 'invalid client_tag: %', p_client_tag;
  END IF;
  IF safe IN ('lp','public','gc','storage','auth','shared','common','default','all')
     OR safe LIKE 'pg_%' THEN
    RAISE EXCEPTION 'client_tag reserved: %', safe;
  END IF;

  profile := lower(coalesce(nullif(btrim(p_profile), ''), 'owner'));
  IF profile NOT IN ('owner', 'service') THEN
    profile := 'owner';
  END IF;

  -- Legacy table names for basco / peterson; _wf_ infix for everyone else.
  IF safe IN ('basco', 'peterson') THEN
    companies := safe || '_companies';
    contacts := safe || '_contacts';
  ELSE
    companies := safe || '_wf_companies';
    contacts := safe || '_wf_contacts';
  END IF;

  IF p_titles IS NULL OR jsonb_typeof(p_titles) <> 'array' OR jsonb_array_length(p_titles) = 0 THEN
    IF profile = 'service' THEN
      titles := '["Service Director","Fixed Operations Director","Fixed Ops Director","Service Manager","Warranty Manager","Warranty Administrator","Director of Service","VP of Service","Vice President of Service","General Manager","Dealer Principal","GM"]'::jsonb;
    ELSE
      titles := '["Owner","Founder","Principal","President","Partner","CEO","Vice President","VP","Director","General Manager"]'::jsonb;
    END IF;
  ELSE
    titles := p_titles;
  END IF;

  IF to_regclass(format('public.%I', companies)) IS NULL THEN
    EXECUTE format($f$
      CREATE TABLE public.%I (
        domain text PRIMARY KEY,
        company_name text,
        source text,
        in_shovels boolean,
        in_maps_icp boolean,
        permit_count integer,
        place text,
        address_city text,
        address_state text,
        employee_range text,
        shovels_email text,
        shovels_name text,
        dm_lookup_status text,
        email_source_tier text,
        dm_source_tier text,
        source_tier jsonb,
        website text,
        client_tag text NOT NULL DEFAULT %L,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT %I CHECK (client_tag = %L)
      )
    $f$, companies, safe, companies || '_client_tag_check', safe);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I (client_tag)', companies || '_client_tag_idx', companies);
    created_companies := true;
  END IF;

  IF to_regclass(format('public.%I', contacts)) IS NULL THEN
    EXECUTE format($f$
      CREATE TABLE public.%I (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        domain text NOT NULL,
        first_name text,
        last_name text,
        job_title text,
        job_level text,
        email text,
        email_status text,
        cellphone text,
        linkedin_url text,
        contact_city text,
        contact_state text,
        source_tool text,
        source_tier text,
        source_url text,
        confidence double precision,
        place_id text,
        client_tag text NOT NULL DEFAULT %L,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        suppressed boolean DEFAULT false,
        CONSTRAINT %I CHECK (client_tag = %L),
        CONSTRAINT %I UNIQUE (domain, email)
      )
    $f$, contacts, safe, contacts || '_client_tag_check', safe, contacts || '_domain_email_key');
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I (domain)', contacts || '_domain_idx', contacts);
    EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON public.%I (client_tag)', contacts || '_client_tag_idx', contacts);
    created_contacts := true;
  END IF;

  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO service_role', companies);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO service_role', contacts);
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role');

  PERFORM pg_notify('pgrst', 'reload schema');

  INSERT INTO public.ew_clients (
    client_tag, display_name, companies_table, contacts_table, profile, titles, icp, updated_at
  ) VALUES (
    safe,
    coalesce(nullif(btrim(p_display_name), ''), safe),
    companies,
    contacts,
    profile,
    titles,
    nullif(btrim(p_icp), ''),
    now()
  )
  ON CONFLICT (client_tag) DO UPDATE SET
    display_name = coalesce(nullif(btrim(EXCLUDED.display_name), ''), public.ew_clients.display_name),
    profile = EXCLUDED.profile,
    titles = EXCLUDED.titles,
    icp = coalesce(EXCLUDED.icp, public.ew_clients.icp),
    updated_at = now();

  RETURN jsonb_build_object(
    'ok', true,
    'client_tag', safe,
    'display_name', coalesce(nullif(btrim(p_display_name), ''), safe),
    'companies_table', companies,
    'contacts_table', contacts,
    'profile', profile,
    'titles', titles,
    'created_companies', created_companies,
    'created_contacts', created_contacts
  );
END;
$$;

REVOKE ALL ON FUNCTION public.ew_ensure_client(text, text, text, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ew_ensure_client(text, text, text, text, jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.ew_list_clients()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT coalesce(
    jsonb_agg(
      jsonb_build_object(
        'client_tag', c.client_tag,
        'display_name', c.display_name,
        'companies_table', c.companies_table,
        'contacts_table', c.contacts_table,
        'profile', c.profile,
        'titles', c.titles,
        'icp', c.icp,
        'created_at', c.created_at
      )
      ORDER BY c.client_tag
    ),
    '[]'::jsonb
  )
  FROM public.ew_clients c;
$$;

REVOKE ALL ON FUNCTION public.ew_list_clients() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ew_list_clients() TO service_role;

-- Seed legacy clients
INSERT INTO public.ew_clients (client_tag, display_name, companies_table, contacts_table, profile, titles, icp)
VALUES
  (
    'basco', 'Carlos', 'basco_companies', 'basco_contacts', 'service',
    '["Service Director","Fixed Operations Director","Fixed Ops Director","Service Manager","Warranty Manager","Warranty Administrator","Director of Service","VP of Service","Vice President of Service","General Manager","Dealer Principal","GM"]'::jsonb,
    'Franchise new-car dealership rooftops near Clifton, NJ.'
  ),
  (
    'peterson', 'Kyle', 'peterson_companies', 'peterson_contacts', 'owner',
    '["Owner","Founder","Principal","President","Partner","CEO","Vice President","VP","Director","General Manager"]'::jsonb,
    'Commercial roofing / GCs / PMs in Dallas-Fort Worth.'
  )
ON CONFLICT (client_tag) DO NOTHING;
